#!/bin/bash

# ALWAYS CLEAN THE PREVIOUS BUILD
git clean -dfx 2>/dev/null 1>/dev/null

# NOTE THAT srt's Tcl ./configure IS DELIBERATELY NOT RUN HERE, UNLIKE ON THE
# OTHER PLATFORMS. IT IS ONLY A WRAPPER THAT TRANSLATES autotools-STYLE OPTIONS
# INTO cmake -D FLAGS, AND THIS SCRIPT PASSES THOSE FLAGS DIRECTLY. ON WINDOWS
# IT ALSO CANNOT COMPLETE: IT CALLS "file attributes ... -permissions +x", AND
# -permissions IS A UNIX-ONLY Tcl ATTRIBUTE, SO IT ABORTS BEFORE PRODUCING
# ANYTHING. NOTHING IN srt's CMakeLists.txt CONSUMES ITS OUTPUT.

# ENABLE_MONOTONIC_CLOCK IS DELIBERATELY NOT SET, UNLIKE ON THE OTHER PLATFORMS.
# srt ONLY PROBES FOR clock_gettime ON ITS POSIX BRANCH, SO THE DEFAULT IS OFF
# HERE AND FORCING IT ON IS A HARD CONFIGURE ERROR. IT TUNES THE pthread CONDVAR
# TIMING, WHICH ENABLE_STDCXX_SYNC BELOW REPLACES WITH C++11 chrono ANYWAY.
cmake -Wno-dev \
 -DUSE_ENCLIB=openssl \
 -DCMAKE_VERBOSE_MAKEFILE=0 \
 -DCMAKE_C_FLAGS="${CFLAGS}" \
 -DCMAKE_CXX_FLAGS="${CXXFLAGS}" \
 -DCMAKE_EXE_LINKER_FLAGS="${LDFLAGS}" \
 -DCMAKE_BUILD_TYPE=Release \
 -DCMAKE_INSTALL_PREFIX="${LIB_INSTALL_PREFIX}" \
 -DCMAKE_SYSTEM_NAME=Windows \
 -DCMAKE_CXX_COMPILER="$CXX" \
 -DCMAKE_C_COMPILER="$CC" \
 -DCMAKE_AR="$AR" \
 -DCMAKE_RC_COMPILER="$WINDRES" \
 -DCMAKE_SYSTEM_PROCESSOR="$(get_cmake_system_processor)" \
 -DENABLE_STDCXX_SYNC=1 \
 -DENABLE_CXX11=1 \
 -DUSE_OPENSSL_PC=1 \
 -DENABLE_DEBUG=0 \
 -DENABLE_LOGGING=0 \
 -DENABLE_HEAVY_LOGGING=0 \
 -DENABLE_APPS=0 \
 -DENABLE_SHARED=0 "${BASEDIR}"/src/"${LIB_NAME}" || return 1

make -j$(get_cpu_count) || return 1

make install || return 1

# CREATE PACKAGE CONFIG MANUALLY
create_srt_package_config "1.5.5" || return 1
